$(function(){
    $("#button1").click(function(){
            $(".img1").fadeIn();
            $(".img2").fadeOut();
            $(".img3").fadeOut();
            $(".img4").fadeOut();
    });	
    $("#button2").click(function(){
            $(".img1").fadeOut();
            $(".img2").fadeIn();
            $(".img3").fadeOut();
            $(".img4").fadeOut();
    });
    $("#button3").click(function(){
            $(".img1").fadeOut();
            $(".img2").fadeOut();
            $(".img3").fadeIn();
            $(".img4").fadeOut();
    });
    $("#button4").click(function(){
            $(".img1").fadeOut();
            $(".img2").fadeOut();
            $(".img3").fadeOut();
            $(".img4").fadeIn();
    });
        $("#button5").click(function(){
                $(".img5").fadeIn();
                $(".img6").fadeOut();
                $(".img7").fadeOut();
                $(".img8").fadeOut();
        });	
        $("#button6").click(function(){
                $(".img5").fadeOut();
                $(".img6").fadeIn();
                $(".img7").fadeOut();
                $(".img8").fadeOut();
        });
        $("#button7").click(function(){
                $(".img5").fadeOut();
                $(".img6").fadeOut();
                $(".img7").fadeIn();
                $(".img8").fadeOut();
        });
        $("#button8").click(function(){
                $(".img5").fadeOut();
                $(".img6").fadeOut();
                $(".img7").fadeOut();
                $(".img8").fadeIn();
        });
        $("#button9").click(function(){
                $(".img9").fadeIn();
                $(".img10").fadeOut();
                $(".img11").fadeOut();
                $(".img12").fadeOut();
        });	
        $("#button10").click(function(){
                $(".img9").fadeOut();
                $(".img10").fadeIn();
                $(".img11").fadeOut();
                $(".img12").fadeOut();
        });
        $("#button11").click(function(){
                $(".img9").fadeOut();
                $(".img10").fadeOut();
                $(".img11").fadeIn();
                $(".img12").fadeOut();
        });
        $("#button12").click(function(){
                $(".img9").fadeOut();
                $(".img10").fadeOut();
                $(".img11").fadeOut();
                $(".img12").fadeIn();
        });
        $("#button13").click(function(){
                $(".img13").fadeIn();
                $(".img14").fadeOut();
                $(".img15").fadeOut();
                $(".img16").fadeOut();
        });	
        $("#button14").click(function(){
                $(".img13").fadeOut();
                $(".img14").fadeIn();
                $(".img15").fadeOut();
                $(".img16").fadeOut();
        });
        $("#button15").click(function(){
                $(".img13").fadeOut();
                $(".img14").fadeOut();
                $(".img15").fadeIn();
                $(".img16").fadeOut();
        });
        $("#button16").click(function(){
                $(".img13").fadeOut();
                $(".img14").fadeOut();
                $(".img15").fadeOut();
                $(".img16").fadeIn();
        });
    });